import type { Question } from "./types";

const STAKEHOLDER_OPTIONS = [
  "결제자",
  "수취자",
  "운영자",
  "관리자",
  "감독기관",
  "정산 파트너",
  "외부 BD 파트너",
  "지갑·커스터디",
  "발행자(issuer)",
];

const WHEN_TX_OPTIONS = [
  "결제 완료",
  "정산 마감",
  "송금 요청",
  "자산 발행·소각",
  "인증 발급",
  "멤버십 등급 변경",
  "에스크로 해제",
  "DEX 매칭 체결",
  "RWA 발행·환매",
];

const WHEN_REPEAT_OPTIONS = ["매일", "주간", "월간", "분기", "이벤트 발생 시", "1회성"];

const WHERE_MARKET_OPTIONS = [
  "핀테크",
  "커머스",
  "콘텐츠·미디어",
  "게임",
  "모빌리티",
  "부동산",
  "헬스케어",
  "교육",
  "공공·B2G",
  "여행·관광",
  "물류·무역",
];

const WHERE_GEO_OPTIONS = ["한국 only", "한국+동남아", "한국+북미", "APAC", "글로벌"];

const WHY_XRPL_OPTIONS = [
  "빠른 결제 (3~5초)",
  "저렴한 수수료",
  "크로스보더 결제 표준",
  "native DEX·토큰 발행",
  "규제 친화 이미지",
  "글로벌 파트너십",
  "한국 커뮤니티 지원",
  "성숙한 네트워크 (10년+ 운영)",
];

const WHY_LEGACY_LIMIT_OPTIONS = [
  "정산 지연",
  "수수료 부담",
  "신뢰 검증 비용",
  "크로스보더 마찰",
  "데이터 위·변조 가능성",
  "중개자 lock-in",
  "데이터 사일로 (타기관 연동 마찰)",
  "감사 추적 어려움",
];

const WHAT_XRPL_FIT_OPTIONS = [
  "결제",
  "정산",
  "송금",
  "토큰화 자산 발행(RWA)",
  "DID·인증",
  "스테이블코인",
  "NFT",
  "에스크로",
  "디지털자산 교환(DEX)",
  "유동성 풀 (AMM)",
  "다중서명 (Multi-sig)",
  "온체인 영수증·증명",
];

const WHAT_ADDON_FULL = [
  "결제",
  "정산",
  "송금",
  "토큰화 자산 발행(RWA)",
  "멤버십·포인트",
  "DID·인증",
  "스테이블코인",
  "NFT",
  "에스크로",
  "디지털자산 교환(DEX)",
  "유동성 풀 (AMM)",
  "다중서명 (Multi-sig)",
  "온체인 영수증·증명",
];

export const QUESTIONS_A: Question[] = [
  {
    key: "who_team",
    mode: "A",
    section: "who",
    label: "우리 팀은 어떤 팀인지",
    type: "single",
    options: [
      "스타트업",
      "중견기업",
      "대기업",
      "금융기관",
      "거래소·VASP",
      "공공·정부",
      "학회·연구실",
      "솔로 메이커",
    ],
  },
  {
    key: "who_customer",
    mode: "A",
    section: "who",
    label: "현재 주요 고객은 누구인지",
    type: "multi",
    options: [
      "B2C 일반 소비자",
      "중소사업자(SME)",
      "대기업",
      "금융기관",
      "공공·정부",
      "개발자·빌더",
      "크리에이터",
      "B2B2C 파트너",
      "거래소·VASP",
      "해외 송금 수요자 (이주노동자·유학생 등)",
    ],
  },
  {
    key: "who_user",
    mode: "A",
    section: "who",
    label: "제품을 실제로 쓰는 주체는 누구인지",
    type: "textarea",
    placeholder: "예: 가맹점 점주, 정산 담당자 등",
  },
  {
    key: "who_stakeholder",
    mode: "A",
    section: "who",
    label: "결제자 / 수취자 / 운영자 / 관리자 등 핵심 이해관계자",
    type: "multi",
    options: STAKEHOLDER_OPTIONS,
  },

  {
    key: "what_problem",
    mode: "A",
    section: "what",
    label: "현재 프로덕트가 해결하려는 문제",
    type: "textarea",
    placeholder: "한 문단 이내로 핵심 문제만",
  },
  {
    key: "what_core_feature",
    mode: "A",
    section: "what",
    label: "현재 제공 중인 핵심 기능",
    type: "multi",
    options: [
      "결제",
      "송금",
      "정산",
      "멤버십·포인트",
      "자산 관리",
      "인증·KYC",
      "마켓플레이스",
      "콘텐츠 유통",
      "디지털자산 매매·교환",
      "쿠폰·티켓·바우처",
      "예약·예치 (보증금)",
    ],
  },
  {
    key: "what_addon",
    mode: "A",
    section: "what",
    label: "앞으로 붙이고 싶은 금융·디지털자산·정산·인증·멤버십 기능",
    type: "multi",
    options: WHAT_ADDON_FULL,
  },
  {
    key: "what_user_value",
    mode: "A",
    section: "what",
    label: "사용자에게 가장 중요한 기능",
    type: "textarea",
    placeholder: "사용자가 가장 자주 쓰거나 가장 가치를 느끼는 기능",
  },

  {
    key: "when_context",
    mode: "A",
    section: "when",
    label: "유저가 이 제품을 언제, 어떤 상황에서 쓰는지",
    type: "multi",
    options: [
      "일상 결제",
      "B2B 정산 사이클",
      "월·분기 정산",
      "이벤트 기반",
      "크로스보더 송금 시점",
      "자산 매수·매도",
      "멤버십 가입·갱신",
      "정기 구독 갱신",
      "조건 충족 시 자동 실행",
    ],
  },
  {
    key: "when_tx",
    mode: "A",
    section: "when",
    label: "거래·정산·결제·송금·자산 이동이 발생하는 시점",
    type: "multi",
    options: WHEN_TX_OPTIONS,
  },
  {
    key: "when_repeat",
    mode: "A",
    section: "when",
    label: "반복 사용이 일어나는 패턴",
    type: "single",
    options: WHEN_REPEAT_OPTIONS,
  },

  {
    key: "where_market",
    mode: "A",
    section: "where",
    label: "제품이 주로 쓰이는 시장·산업·환경",
    type: "multi",
    options: WHERE_MARKET_OPTIONS,
  },
  {
    key: "where_geo",
    mode: "A",
    section: "where",
    label: "지역 범위",
    type: "single",
    options: WHERE_GEO_OPTIONS,
  },
  {
    key: "where_online_offline",
    mode: "A",
    section: "where",
    label: "온오프라인 중 어디서 주로 쓰이는지",
    type: "segment",
    options: ["온라인", "오프라인", "옴니채널 (혼합)"],
  },
  {
    key: "where_business_model",
    mode: "A",
    section: "where",
    label: "비즈니스 모델",
    type: "segment",
    options: ["B2B", "B2C", "B2B2C", "B2G"],
  },

  {
    key: "why_problem",
    mode: "A",
    section: "why",
    label: "왜 이 문제를 해결하려고 하는지",
    type: "textarea",
    placeholder: "팀이 이 문제에 끌리는 진짜 이유",
  },
  {
    key: "why_xrpl",
    mode: "A",
    section: "why",
    label: "XRPL 의 어떤 특성을 우리 제품에서 살리고 싶은지",
    type: "multi",
    options: WHY_XRPL_OPTIONS,
  },
  {
    key: "why_web2_limit",
    mode: "A",
    section: "why",
    label: "기존 Web2 방식으로 해결하기 어려운 지점",
    type: "multi",
    options: WHY_LEGACY_LIMIT_OPTIONS,
  },
  {
    key: "why_xrpl_value",
    mode: "A",
    section: "why",
    label: "사용자나 비즈니스 입장에서 XRPL 이 들어갔을 때 더 좋아지는 점",
    type: "textarea",
    placeholder: "구체적으로 사용자 경험이나 KPI 가 어떻게 달라지는지",
  },
  {
    key: "why_business_impact",
    mode: "A",
    section: "why",
    label: "단순 홍보용이 아니라 실제 비즈니스 성과와 연결될 수 있는 이유",
    type: "textarea",
    placeholder: "예: 정산 주기 단축으로 운영 자본 회수, 신규 고객 유치 등",
  },

  {
    key: "how_works",
    mode: "A",
    section: "how",
    label: "현재 제품은 어떤 방식으로 작동하는지",
    type: "textarea",
    placeholder: "사용자가 처음 진입해서 가치를 얻기까지의 흐름",
  },
  {
    key: "how_flow",
    mode: "A",
    section: "how",
    label: "현재 제품에 어떤 흐름이 있는지 (결제·정산·송금·멤버십 등)",
    type: "multi",
    options: ["결제", "정산", "자산 관리", "포인트·멤버십", "송금", "인증", "콘텐츠 유통"],
  },
  {
    key: "how_stack",
    mode: "A",
    section: "how",
    label: "현재 기술 스택",
    type: "multi",
    options: [
      "Node.js",
      "Python",
      "Java·Kotlin",
      "React·Next.js",
      "Swift / iOS 네이티브",
      "Flutter",
      "자체 백엔드",
      "AWS",
      "GCP",
      "Azure",
      "블록체인·Web3 개발 경험",
    ],
  },
  {
    key: "how_team_capacity",
    mode: "A",
    section: "how",
    label: "우리 팀의 개발 역량과 제약",
    type: "textarea",
    placeholder: "인력 규모, 강한 영역, 외주 의존 여부 등",
  },
  {
    key: "how_partners",
    mode: "A",
    section: "how",
    label: "외부 파트너나 고객사가 있다면 어떤 역할을 하는지",
    type: "textarea",
    placeholder: "정산·BD·기술 통합 등 파트너의 위치",
  },

  {
    key: "extra_team",
    mode: "A",
    section: "extra",
    label: "현재 팀 구성",
    type: "textarea",
    placeholder: "예: PM 1, FE 2, BE 1, 디자이너 1",
  },
  {
    key: "extra_mvp",
    mode: "A",
    section: "extra",
    label: "8~12주 안에 만들 수 있는 MVP 범위",
    type: "textarea",
    placeholder: "현실적으로 8~12주 안에 출시할 수 있는 가장 작은 단위",
  },
  {
    key: "extra_keep",
    mode: "A",
    section: "extra",
    label: "꼭 유지해야 하는 기존 제품 요소",
    type: "textarea",
    placeholder: "기존 사용자 경험·정산 구조·파트너 계약 등 건드리면 안 되는 부분",
  },
  {
    key: "extra_hypothesis",
    mode: "A",
    section: "extra",
    label: "반드시 검증하고 싶은 가설",
    type: "textarea",
    placeholder: "예: '온체인 영수증을 발급해도 사용자 이탈률이 늘지 않는다'",
  },
  {
    key: "extra_uncertain",
    mode: "A",
    section: "extra",
    label: "아직 확신이 없는 부분",
    type: "textarea",
    placeholder: "기술·규제·시장·운영 어느 쪽이든",
  },
  {
    key: "extra_concern",
    mode: "A",
    section: "extra",
    label: "특히 고민되는 XRPL 적용 포인트",
    type: "textarea",
    placeholder: "기술적 난이도·사용자 경험·규제 측면에서 막막한 지점",
  },
];

export const QUESTIONS_B: Question[] = [
  {
    key: "who_need",
    mode: "B",
    section: "who",
    label: "이 아이디어가 필요한 사용자",
    type: "multi",
    options: [
      "B2C 일반 소비자",
      "중소사업자(SME)",
      "대기업",
      "금융기관",
      "공공·정부",
      "개발자·빌더",
      "크리에이터",
      "B2B2C 파트너",
      "거래소·VASP",
      "해외 송금 수요자 (이주노동자·유학생 등)",
    ],
  },
  {
    key: "who_early",
    mode: "B",
    section: "who",
    label: "가장 먼저 써볼 수 있는 핵심 사용자군",
    type: "textarea",
    placeholder: "구체적인 1차 타겟 (예: 서울 강남 디자인 스튜디오 운영자)",
  },
  {
    key: "who_stakeholder",
    mode: "B",
    section: "who",
    label: "결제자 / 수취자 / 운영자 / 관리자 등 이해관계자",
    type: "multi",
    options: STAKEHOLDER_OPTIONS,
  },
  {
    key: "who_buyer_vs_user",
    mode: "B",
    section: "who",
    label: "실제 구매자와 사용자가 다른지",
    type: "single",
    options: ["같다", "다르다 (B2B2C)", "다르다 (B2G → 시민)", "모름"],
  },

  {
    key: "what_make",
    mode: "B",
    section: "what",
    label: "내가 만들고 싶은 것",
    type: "textarea",
    placeholder: "한 문단으로 자유롭게",
  },
  {
    key: "what_oneliner",
    mode: "B",
    section: "what",
    label: "이 아이디어를 한 줄로 설명하면",
    type: "textarea",
    placeholder: "예: '동남아 송금 노동자를 위한 XRPL 기반 즉시 정산 지갑'",
  },
  {
    key: "what_problem",
    mode: "B",
    section: "what",
    label: "해결하려는 문제",
    type: "textarea",
    placeholder: "어떤 사용자의 어떤 문제인지",
  },
  {
    key: "what_features",
    mode: "B",
    section: "what",
    label: "지금 떠올리고 있는 핵심 기능",
    type: "multi",
    options: WHAT_ADDON_FULL,
  },
  {
    key: "what_xrpl_fit",
    mode: "B",
    section: "what",
    label: "블록체인·XRPL 이 들어갈 것 같은 기능",
    type: "multi",
    options: WHAT_XRPL_FIT_OPTIONS,
  },

  {
    key: "when_use",
    mode: "B",
    section: "when",
    label: "사용자가 언제 이 서비스를 쓰게 될 것 같은지",
    type: "textarea",
    placeholder: "사용 맥락 (장소·시간·상황)",
  },
  {
    key: "when_tx",
    mode: "B",
    section: "when",
    label: "거래·정산·송금·자산 이동·인증이 발생할 것 같은 시점",
    type: "multi",
    options: WHEN_TX_OPTIONS,
  },
  {
    key: "when_repeat",
    mode: "B",
    section: "when",
    label: "반복 사용이 일어날 타이밍",
    type: "single",
    options: WHEN_REPEAT_OPTIONS,
  },

  {
    key: "where_market",
    mode: "B",
    section: "where",
    label: "이 아이디어가 적용될 시장·산업·사용 환경",
    type: "multi",
    options: WHERE_MARKET_OPTIONS,
  },
  {
    key: "where_geo",
    mode: "B",
    section: "where",
    label: "지역 범위",
    type: "single",
    options: WHERE_GEO_OPTIONS,
  },
  {
    key: "where_context",
    mode: "B",
    section: "where",
    label: "사용 맥락",
    type: "single",
    options: [
      "온라인 B2C",
      "오프라인 B2C",
      "B2B SaaS",
      "B2B 정산·결제",
      "B2G",
      "옴니채널",
    ],
  },
  {
    key: "where_initial_partner",
    mode: "B",
    section: "where",
    label: "초기 고객이나 파트너로 상정할 수 있는 곳",
    type: "textarea",
    placeholder: "이름이 떠오르는 회사·기관·커뮤니티",
  },

  {
    key: "why_important",
    mode: "B",
    section: "why",
    label: "왜 이 문제를 중요하다고 느끼는지",
    type: "textarea",
    placeholder: "본인이 이 문제에 끌리는 진짜 이유",
  },
  {
    key: "why_legacy_limit",
    mode: "B",
    section: "why",
    label: "기존 방식의 한계",
    type: "multi",
    options: WHY_LEGACY_LIMIT_OPTIONS,
  },
  {
    key: "why_xrpl",
    mode: "B",
    section: "why",
    label: "XRPL 이나 디지털 자산의 어떤 특성을 이 아이디어에서 살리고 싶은지",
    type: "multi",
    options: WHY_XRPL_OPTIONS,
  },
  {
    key: "why_user_need",
    mode: "B",
    section: "why",
    label: "사용자 입장에서 이 서비스가 왜 필요한지",
    type: "textarea",
    placeholder: "사용자가 느끼는 가치 또는 통증",
  },
  {
    key: "why_business",
    mode: "B",
    section: "why",
    label: "비즈니스 관점에서 이 아이디어가 의미 있는 이유",
    type: "textarea",
    placeholder: "수익 구조·시장 크기·파트너십 가능성",
  },

  {
    key: "how_flow",
    mode: "B",
    section: "how",
    label: "지금 머릿속에 있는 사용자 흐름",
    type: "textarea",
    placeholder: "사용자가 처음 진입해서 핵심 가치를 얻는 순서",
  },
  {
    key: "how_xrpl_point",
    mode: "B",
    section: "how",
    label: "XRPL 이나 디지털 자산이 들어갈 것 같은 부분",
    type: "multi",
    options: WHAT_XRPL_FIT_OPTIONS,
  },
  {
    key: "how_team",
    mode: "B",
    section: "how",
    label: "현재 팀 구성과 개발 가능 여부",
    type: "single",
    options: [
      "1인",
      "2~3인 (개발자 포함)",
      "2~3인 (비개발)",
      "4~10인",
      "외주 활용 예정",
      "미정",
    ],
  },
  {
    key: "how_strength",
    mode: "B",
    section: "how",
    label: "내가 가진 강점과 부족한 점",
    type: "textarea",
    placeholder: "강점·약점 자유 서술",
  },
  {
    key: "how_first_mvp",
    mode: "B",
    section: "how",
    label: "MVP 를 만든다면 가장 먼저 구현해야 할 흐름",
    type: "textarea",
    placeholder: "한 문장으로 '무엇을 통해 무엇을 검증할지'",
  },

  {
    key: "extra_team",
    mode: "B",
    section: "extra",
    label: "현재 팀 구성",
    type: "textarea",
    placeholder: "인원·역할·외부 도움 등",
  },
  {
    key: "extra_mvp",
    mode: "B",
    section: "extra",
    label: "8~12주 안에 만들 수 있는 MVP 범위",
    type: "textarea",
    placeholder: "현실적으로 8~12주 안에 출시할 수 있는 가장 작은 단위",
  },
  {
    key: "extra_must",
    mode: "B",
    section: "extra",
    label: "꼭 구현하고 싶은 기능",
    type: "textarea",
    placeholder: "MVP 시점에 반드시 있어야 한다고 느끼는 기능",
  },
  {
    key: "extra_hypothesis",
    mode: "B",
    section: "extra",
    label: "반드시 검증하고 싶은 가설",
    type: "textarea",
    placeholder: "예: '사용자가 지갑 설치 없이 결제하면 전환율이 X% 이상'",
  },
  {
    key: "extra_uncertain",
    mode: "B",
    section: "extra",
    label: "아직 확신이 없는 기능",
    type: "textarea",
    placeholder: "기술·규제·수요 측면에서 흔들리는 부분",
  },
  {
    key: "extra_concern",
    mode: "B",
    section: "extra",
    label: "가장 고민되는 부분",
    type: "textarea",
    placeholder: "솔직하게 적기. 답이 안 나오는 지점도 OK",
  },
];

export function getQuestions(mode: "A" | "B"): Question[] {
  return mode === "A" ? QUESTIONS_A : QUESTIONS_B;
}
